# This is a generated file. Not intended for manual editing.
services:
  gateway:
    build:
      context: "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect"
      dockerfile: "Gateway.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Gateway.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "gateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\An\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect\\Gateway.Presentation:/app:rw"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect:/src:rw"
    working_dir: "/app"
  home:
    build:
      context: "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect"
      dockerfile: "Home.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Home.Presentation.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Home.Presentation.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "home:dev"
    ports: []
    volumes:
    - "C:\\Users\\An\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect\\Home.Presentation:/app:rw"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect:/src:rw"
    working_dir: "/app"
  identity_provider:
    build:
      context: "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect"
      dockerfile: "IdentityProvider/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/IdentityProvider.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/IdentityProvider.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "identity_provider:dev"
    ports: []
    volumes:
    - "C:\\Users\\An\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect\\IdentityProvider:/app:rw"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect:/src:rw"
    working_dir: "/app"
  oidc:
    build:
      context: "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect"
      dockerfile: "Oidc.Presentation/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Oidc.Presentation.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "oidc:dev"
    ports: []
    volumes:
    - "C:\\Users\\An\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect\\Oidc.Presentation:/app:rw"
    - "C:\\Users\\An\\Documents\\Projects\\be-dot-net\\Utconnect:/src:rw"
    working_dir: "/app"
