networks:
  backend:

volumes:
  identity_provider_data_db:
  oidc_data_db:

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    container_name: gateway
    build:
      context: .
      dockerfile: Gateway.Presentation/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
      - ./DataProtectionKeys:/home/app/.aspnet/DataProtection-Keys
    networks:
      - backend

  home:
    image: ${DOCKER_REGISTRY-}home
    container_name: home
    build:
      context: .
      dockerfile: Home.Presentation/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORT=8080
    networks:
      - backend

  identity_provider:
    image: ${DOCKER_REGISTRY-}identity_provider
    container_name: identity_provider
    build:
      context: .
      dockerfile: IdentityProvider/Dockerfile
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_HTTPS_PORT=8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - backend
    depends_on:
      identity_provider_db:
        condition: service_healthy

  oidc:
    image: ${DOCKER_REGISTRY-}oidc
    container_name: oidc
    build:
      context: .
      dockerfile: Oidc.Presentation/Dockerfile
    networks:
      - backend
    depends_on:
      oidc_db:
        condition: service_healthy

  identity_provider_db:
    container_name: identity_provider_db
    image: postgres:16.3
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Identity
    volumes:
      - identity_provider_data_db:/var/lib/postgresql/data
      - ./Docker/IdentityProvider:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  oidc_db:
    container_name: oidc_db
    image: postgres:16.3
    restart: always
    ports:
      - "54322:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Oidc
    volumes:
      - oidc_data_db:/var/lib/postgresql/data
      - ./Docker/Oidc:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  https_portal:
    container_name: https_portal
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'identity.utcketnoi.local.com => http://identity_provider:8080, utcketnoi.local.com => http://gateway:8080'